spring:
  application:
    name: expense-tracker
  datasource:
    url: ${DB_URL:jdbc:h2:mem:devDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:""}
#    driverClassName: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    properties:
      hibernate:
        format_sql: true
#      hibernate:
#        dialect: ${DB_DIALECT:H2}
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

#  sql:
#    init:
#      mode: always
#  batch:
#    jdbc:
#      initialize-schema: always